# Copyright (c) 2024 The ZMK Contributors
# SPDX-License-Identifier: MIT

# Dongle connects to PC via USB only — no BLE to host
CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=n

# Two BLE peripherals: left half + right half
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

CONFIG_BT_MAX_CONN=3
CONFIG_BT_MAX_PAIRED=3

CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

CONFIG_BT_CTLR_PHY_2M=n
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n
